Repository S-V-23-BootCamp-Team-F/frontend, pull requests merged in 2023-01, with the labels that each got.

#12 design/#6 히스토리 페이지 퍼블리싱
  src/App.tsx
  src/assets/components/Diseased.tsx
  src/assets/components/Healthy.tsx
  src/assets/images/category.svg
  src/assets/images/delete.svg
  src/assets/images/grass.svg
  src/assets/images/logo.svg
  src/pages/HistoryPage.tsx
  tailwind.config.cjs
Labels: UI디자인

#14 design/#7 결과페이지(질병O) 퍼블리싱
  src/App.tsx
  src/images/dietomato.png
  src/images/leaf.png
  src/images/tomato.jpg
  src/images/tomato2.jpg
  src/images/tomato3.jpg
  src/index.css
  src/media.css
  src/pages/AbnomalResultPage.tsx
  tailwind.config.cjs
Labels: UI디자인

#20 fix/#18 퍼블리싱 merge 오류 수정
  src/assets/images/category.svg
  src/assets/images/logo.svg
  src/components/Diseased.tsx
  src/components/Healthy.tsx
  src/components/Navbar.tsx
  src/images/delete.svg
  src/images/grass.svg
  src/pages/AbnomalResultPage.tsx
  src/pages/HistoryPage.tsx
  src/pages/MainPage.tsx
  tailwind.config.cjs
Labels: 오류수정

#25 결과 페이지 (정상) 퍼블리싱
  src/App.tsx
  src/images/nomal.png
  src/pages/NomalResultPage.tsx
Labels: UI디자인

#45 Feat/#33
  index.tsx
  src/api.ts
  src/components/LogInPage.tsx
  src/pages/GetStart.tsx
  src/pages/MainPage.tsx
Labels: 기능구현

#50 fix : 히스토리 페이지 오류 수정
  src/components/Diseased.tsx
  src/pages/HistoryPage.tsx
Labels: 오류수정

#65 비정상 결과 페이지 UI/UX 수정
  src/components/SignupPage.tsx
  src/media.css
  src/pages/AbnomalResultPage.tsx
  src/pages/NomalResultPage.tsx
Labels: 오류수정, UI디자인

#58 ai 진단내용(비정상)에 따른 결과페이지 api 연동
  src/components/SignupPage.tsx
  src/pages/AbnomalResultPage.tsx
  src/pages/MainPage.tsx
Labels: 기능구현

#70 로그인 refresh 토큰 확인 api 전송
  index.tsx
  src/api.ts
  src/components/LogInPage.tsx
  src/main.tsx
  src/pages/AbnomalResultPage.tsx
  src/utils/api.ts
  tsconfig.json
Labels: 기능구현

#73 새로고침시 authorization 풀림 수정
  src/utils/api.ts
Labels: 오류수정, 기능구현

#76 로딩 페이지 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/LoadingPage.tsx
  src/main.tsx
  src/pages/AbnomalResultPage.tsx
  src/pages/GetStart.tsx
  src/pages/HistoryPage.tsx
  src/pages/MainPage.tsx
  src/pages/NomalResultPage.tsx
Labels: 기능구현

#78 변경된 api로 로그인 api 연결 (토큰부분)
  src/components/LogInPage.tsx
  src/utils/api.ts
Labels: 기능구현

#80 Feat/#68 히스토리 상세페이지 퍼블리싱 및 구현
  package-lock.json
  package.json
  src/components/DetailModalscreen.tsx
  src/components/Historycard.tsx
  src/components/SignupPage.tsx
  src/pages/AbnomalResultPage.tsx
  src/pages/HistoryPage.tsx
  src/pages/MainPage.tsx
Labels: 기능구현, UI디자인

#83 Refactor/#81 히스토리 페이지 코드 리팩토링
  src/components/DetailModalscreen.tsx
  src/components/Historycard.tsx
  src/pages/HistoryPage.tsx
Labels: 리팩토링

#89 api 수정사항 변경
  src/pages/AbnomalResultPage.tsx
  src/pages/MainPage.tsx
  src/pages/NomalResultPage.tsx
Labels: 오류수정

#92 로딩메세지 수정
  src/components/LoadingPage.tsx
Labels: 오류수정

#98 Design/#94 히스토리 페이지 애니메이션 추가
  src/components/DetailModalscreen.tsx
Labels: UI디자인

#110 Design/#109 차트 페이지 퍼블리싱
  package-lock.json
  package.json
  src/App.tsx
  src/components/Cropchart.tsx
  src/components/Historycard.tsx
  src/components/Periodchart.tsx
  src/pages/HistoryPage.tsx
  src/pages/StasticsPage.tsx
Labels: UI디자인

#115 Design/#111 차트 퍼블리싱
  src/components/Cropchart.tsx
  src/components/Periodchart.tsx
  src/pages/StasticsPage.tsx
  tailwind.config.cjs
Labels: UI디자인

#119 Feat/#118 linechart api 연동
  src/components/Periodchart.tsx
  src/pages/StasticsPage.tsx
Labels: 기능구현

#120 refactor/#116 회원가입, 로그인, cookie.ts Type 수정
  src/Cookie.ts
  src/components/LogInPage.tsx
  src/components/SignupPage.tsx
  src/pages/GetStart.tsx
Labels: 리팩토링

#122 Feat/#121 네비게이션 바 현재 링크 강조
  src/components/Hamnav.tsx
  src/components/Longnav.tsx
  src/components/Navbar.tsx
  src/images/statistics.svg
  src/images/statistics_hover.svg
  tailwind.config.cjs
Labels: UI디자인

#127 design : Statistic 페이지 배경 나뭇잎삭제
  src/pages/StasticsPage.tsx
Labels: UI디자인

#128 fix/#104 히스토리 페이지 렌더링 작업 및 메인 페이지 버튼 활성화
  src/components/Historycard.tsx
  src/pages/HistoryPage.tsx
  src/pages/MainPage.tsx
Labels: 기능구현

#129 design : 선 설명 추가
  src/components/Navbar.tsx
  src/components/Periodchart.tsx
  src/components/Periodline.tsx
Labels: UI디자인

#132 design : 카테고리 디자인 수정
  src/pages/HistoryPage.tsx
Labels: UI디자인

#138 feat : 진단 실패시 alert창
  src/pages/MainPage.tsx
Labels: 기능구현

#137 Feat/#112 차트 api 연결 및 차트 페이지 디자인
  src/components/Cropchart.tsx
  src/components/Periodchart.tsx
  src/components/Periodline.tsx
  src/pages/HistoryPage.tsx
  src/pages/StasticsPage.tsx
  tailwind.config.cjs
Labels: 기능구현, UI디자인

#141 design : 모달창 정상 마스코트 추가
  src/components/DetailModalscreen.tsx
Labels: UI디자인

#143 design : statistic페이지 요약문 추가
  src/components/Periodchart.tsx
  src/pages/StasticsPage.tsx
Labels: UI디자인
